### ISSUE TITLE
comment request: network connection

### ISSUE THREAD

**Issue by benjyz** [SaitoTech/saito-rust-workspace#273]
what is the reasoning for several types of network connections warp and Tungstenite? comment would be helpful

https://github.com/SaitoTech/saito-rust-workspace/blob/develop/saito-rust/src/saito/network_controller.rs#L51

**Comment by SankaD** [comment]
Because same class is supporting incoming clients and outgoing clients (server side and client side). I have wrapped those lib usages around an enum to generalise the usage. 

Any suggestions are welcome.

**Comment by SankaD** [comment]
Can I close this? or do you have any questions regarding this? @benjyz

**Comment by benjyz** [comment]
no, I understand now. I suggest potentially to move the HTTP requests to websocket type requests, and potentially adopt sth like https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md

**Comment by SankaD** [comment]
So regarding the HTTP requests, those are probably will be served outside of nodes (from caching servers,etc...). It's an intentional change for now.

Regarding RPC, we have a very basic kind of such functionality. but it's still evolving so nothing set in stone yet. It will hopefully will evolve with future requirements/changes.
